baseURL = "https://riightx.github.io/"
languageCode = "en-us"
title = "Riight WoW pages"

theme = "npq"

[markup.goldmark.renderer]
unsafe = true

[params]
custom_css = ["css/style.css"]

    author = "Riight"
    description = "your description"
    keywords = "World of Warcraft healing microsite"
    useAvatar = false
    microBlogSection = "posts"
    displayMicroBlog = true
    displayRecent = true
    recentMax = 4

[menu]
    [[menu.main]]
      name = "home"
      pre = "<i class=\"fas fa-home fa-sm\"></i>"
      url = "/"
      weight = -9
    [[menu.main]]
      name = "tags"
      pre = "<i class=\"fas fa-tags fa-ms\"></i>"
      url = "/tags"
      weight = -7